# Generated by Django 4.2.1 on 2023-06-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("name", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("region1", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("genre", models.CharField(max_length=255)),
                ("difficulty", models.IntegerField()),
                ("fear", models.IntegerField()),
                ("activity", models.IntegerField()),
                ("room_intro", models.TextField()),
            ],
        ),
    ]
